In [1]:
import numpy as np


In [5]:
preds = np.zeros([5, 6])

In [6]:
for i in range(0,5):
    preds[i] = [1,2,3,4,5,6]

In [7]:
print(preds)

[[ 1.  2.  3.  4.  5.  6.]
 [ 1.  2.  3.  4.  5.  6.]
 [ 1.  2.  3.  4.  5.  6.]
 [ 1.  2.  3.  4.  5.  6.]
 [ 1.  2.  3.  4.  5.  6.]]
